<?php

/**
 * @file
 * Contains ipsum.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ipsum_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ipsum module.
    case 'help.page.ipsum':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}
